name: Test GitHub Actions

on:
  pull_request:
  workflow_dispatch:

jobs:
  test-libmamba-solver:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: "3.x"

    - name: Update conda
      run: |
        conda --version
        time conda update -q conda
        conda --version

    - name: Time environment creation (classic)
      run: |
        time conda env create -q --file environment.yml
        conda env remove --name test-env

    - name: Time solver installation
      run: |
        time conda install -q conda-libmamba-solver
        conda config --set solver libmamba

    - name: 'Workaround for mamba-org/mamba#488'
        run: rm /usr/share/miniconda/pkgs/cache/*.json

    - name: Time environment creation (libmamba)
      run: |
        time conda env create -q --file environment.yml
        conda env remove --name test-env

